version: v1
kind: Configuration
metadata:
  name: testing
  labels:
    algorithm: "pygmo.sade"
    test: test
spec:
  logging: INFO
  database: "/tmp/dftfit/database.db"
  steps: 1
  population: 7
  algorithm:
    name: 'pygmo.sade'
  problem:
    # specified calculator is intentionally left out.
    w_f: 0.3
    w_s: 0.6
    w_e: 0.1
  training:
    cache_filename: "test_files/dftfit_calculators/cache/cache.db"
