version: v1
kind: Configuration
metadata:
  name: testing
  labels:
    algorithm: "pygmo.cmaes"
    test: test
spec:
  logging: INFO
  database:
    filename: "/tmp/dftfit/database.db"
    interval: 10
  algorithm:
    name: 'pygmo.cmaes'
    steps: 5
    population: 8
    include_initial_guess: False
    force_bounds: True
  problem:
    calculator: 'lammps_cython'
    num_workers: 2
    weights:
      forces: 0.3
      stress: 0.6
      energy: 0.1
  training:
    cache_filename: "./cache/cache.db"
