variables:
    TWINE_USERNAME: SECURE
    TWINE_PASSWORD: SECURE
    TWINE_REPOSITORY_URL: https://upload.pypi.org/legacy/

stages:
  - test
  - deploy

test_not_calculators:
  image: python:3.6
  stage: test
  script:
    - pip install .
    - python setup.py test --addopts '-m "not calculator"'

test_calculators:
  image: costrouc/lammps:patch_11May2018-debian-mpi-all
  stage: test
  script:
    # install python3.6...
    - apt update
    - apt install libreadline-gplv2-dev libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev -y
    - wget https://www.python.org/ftp/python/3.6.6/Python-3.6.6.tar.xz
    - tar xf Python-3.6.6.tar.xz
    - cd Python-3.6.6
    - ./configure && make && make install
    - cd ..
    - rm -rf Python-3.6.6
    # now run tests
    - python3.6 -m pip install numpy cython mpi4py
    - python3.6 -m pip install . lammps-cython pymatgen_lammps
    - python3.6 setup.py test --addopts '-m "calculator"'

deploy_pypi:
  stage: deploy
  image: python:3.6
  script:
    - pip install -U twine setuptools
    - pip list
    - python setup.py sdist bdist_wheel
    - echo "======== Deploying Package to PyPi ========="
    - twine upload dist/*.tar.gz
    - twine upload dist/*.whl
    - echo "============================================"
  only:
    - /^v\d+\.\d+\.\d+([abc]\d*)?$/  # PEP-440 compliant version (tags)


deploy_docker_dftfit_base:
  image: docker:git
  services:
    - docker:dind
  script:
    - export PKG_VERSION=${CI_COMMIT_TAG:12}
    - export GITLAB_IMAGE="$CI_REGISTRY/$CI_PROJECT_PATH/base"
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build -t $GITLAB_IMAGE:$PKG_VERSION -f Dockerfile.base --build-arg VERSION=$PKG_VERSION .
    - docker push $GITLAB_IMAGE:$PKG_VERSION
  only:
    - /^dftfit_base_[A-Za-z]+_\d+[A-Za-z]+\d+$/
