language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev
addons:
  apt:
    packages:
      - gfortran
      - libopenblas-dev
      - liblapack-dev
install:
  - travis_wait 30 pip install .
script:
  - python setup.py test
