version: v1
kind: Training
spec:
  - type: ground_state
    format: cif
    data: |
      data_MgO
      _symmetry_space_group_name_H-M   'P 1'
      _cell_length_a 4.217(1)
      _cell_length_b 4.217(1)
      _cell_length_c 4.217(1)
      _cell_angle_alpha 90.
      _cell_angle_beta 90.
      _cell_angle_gamma 90.
      _symmetry_space_group_name_H-M 'F m -3 m'
      _symmetry_Int_Tables_number 225
      loop_
      _atom_site_type_symbol
      _atom_site_label
      _atom_site_symmetry_multiplicity
      _atom_site_fract_x
      _atom_site_fract_y
      _atom_site_fract_z
      _atom_site_occupancy
      Mg  Mg1  1  0.000000  0.000000  0.000000  1
      O  O2  1  0.500000  0.500000  0.500000  1
  - type: lattice_constants
    data: [[4.2, 4.2, 4.2], [90, 90, 90]]
  - type: elastic_constants
    data: [[273,  91,  91,   0,   0,   0],
           [ 91, 273,  91,   0,   0,   0],
           [ 91,  91, 273,   0,   0,   0],
           [  0,   0,   0, 141,   0,   0],
           [  0,   0,   0,   0, 141,   0],
           [  0,   0,   0,   0,   0, 141]]
