version: v1
kind: Training
spec:
  - type: mattoolkit
    selector:
      labels:
        - project:potential_fitting
        - "structrue:MgO"
        - calculation_type:static
        - "calculation_group:lattice_constant"
  - type: mattoolkit
    selector:
      labels:
        - project:potential_fitting
        - "structure:MgO"
        - calculation_type:static
        - "calculation_group:phonon_displacements"
  - type: ground_state
    format: cif
    data: |
      data_MgO
      _symmetry_space_group_name_H-M   'P 1'
      _cell_length_a   4.25648319
      _cell_length_b   4.25648319
      _cell_length_c   4.25648319
      _cell_angle_alpha   90.00000000
      _cell_angle_beta   90.00000000
      _cell_angle_gamma   90.00000000
      _symmetry_Int_Tables_number   1
      _chemical_formula_structural   MgO
      _chemical_formula_sum   'Mg4 O4'
      _cell_volume   77.11746928
      _cell_formula_units_Z   4
      loop_
       _symmetry_equiv_pos_site_id
       _symmetry_equiv_pos_as_xyz
        1  'x, y, z'
      loop_
       _atom_site_type_symbol
       _atom_site_label
       _atom_site_symmetry_multiplicity
       _atom_site_fract_x
       _atom_site_fract_y
       _atom_site_fract_z
       _atom_site_occupancy
        Mg  Mg1  1  0.000000  0.000000  0.000000  1
        Mg  Mg2  1  0.000000  0.500000  0.500000  1
        Mg  Mg3  1  0.500000  0.000000  0.500000  1
        Mg  Mg4  1  0.500000  0.500000  0.000000  1
        O  O5  1  0.500000  0.000000  0.000000  1
        O  O6  1  0.500000  0.500000  0.500000  1
        O  O7  1  0.000000  0.000000  0.500000  1
        O  O8  1  0.000000  0.500000  0.000000  1
  - type: lattice_constants
    data: [[4.2, 4.2, 4.2], [90, 90, 90]]
  - type: elastic_constants
    data: [[273,  91,  91,   0,   0,   0],
           [ 91, 273,  91,   0,   0,   0],
           [ 91,  91, 273,   0,   0,   0],
           [  0,   0,   0, 141,   0,   0],
           [  0,   0,   0,   0, 141,   0],
           [  0,   0,   0,   0,   0, 141]]
  - type: bulk_modulus
    data: 151
  - type: shear_modulus
    data: 119
  - type: point_defects
    data:
      # from Ben's dissertation
      mg_interstial:
        - {"opp": "+", "element": "Mg", "position": [0.5, 0.5, 0.0], "energy": -1.0}
      o_interstial:
        - {"opp": "+", "element": "O", "position": [0.5, 0.5, 0.0], "energy": -3.5}
      mg_vacancy:
        - {"opp": "-", "element": "Mg", "position": [0.0, 0.0, 0.0], "energy": -1.0}
      o_vacancy:
        - {"opp": "-", "element": "O", "position": [0.5, 0.5, 0.5], "energy": 1.8}
  - type: displacement_energies
    data:
      # from Ben's dissertation
      mg_1: { "element": "Mg", "position": [0, 0, 0], "direction": [1, 0, 0], "energy": 122.5}
      mg_2: { "element": "Mg", "position": [0, 0, 0], "direction": [1, 1, 0], "energy": 29.5}
      mg_3: { "element": "Mg", "position": [0, 0, 0], "direction": [1, 1, 1], "energy": 122.5}
      o_1: { "element": "O", "position": [0.5, 0.5, 0.5], "direction": [1, 0, 0], "energy": 150.0}
      o_2: { "element": "O", "position": [0.5, 0.5, 0.5], "direction": [1, 1, 0], "energy": 25.5}
      o_3: { "element": "O", "position": [0.5, 0.5, 0.5], "direction": [1, 1, 1], "energy": 65.5}
