version: v1
kind: Training
spec:
  # - type: Siesta
  #   selector:
  #     filename: test_files/siesta/d1_li_20ev.xml
  #     num_samples: 3
  # - type: Siesta
  #   selector:
  #     filename: test_files/siesta/d1_o_30ev.xml
  #     num_samples: 4
  - type: Siesta
    selector:
      filename: test_files/siesta/d3_o_20ev.xml
      num_samples: 5
