version: v1
kind: Training
spec:
  - type: Siesta
    selector:
      fileglob: ../data/abinitio/litao3/d1_*ev.xml
      num_samples: 4
  - type: ground_state
    format: cif
    # crystalography.net (1531051)
    data: |
      data_1531051
      _chemical_formula_sum            'Li O3 Ta'
      _chemical_name_systematic        'Li (Ta O3)'
      _space_group_IT_number           167
      _symmetry_space_group_name_Hall  '-R 3 2"c'
      _symmetry_space_group_name_H-M   'R -3 c :H'
      _cell_angle_alpha                90
      _cell_angle_beta                 90
      _cell_angle_gamma                120
      _cell_formula_units_Z            6
      _cell_length_a                   5.15428
      _cell_length_b                   5.15428
      _cell_length_c                   13.7835
      _cell_volume                     317.122
      loop_
      _atom_site_label
      _atom_site_type_symbol
      _atom_site_fract_x
      _atom_site_fract_y
      _atom_site_fract_z
      _atom_site_occupancy
      _atom_site_U_iso_or_equiv
      O1 O-2 0.0501 0.3436 0.0687 1.0 0.0
      Ta1 Ta+5 0 0 0 1.0 0.0
      Li1 Li+1 0 0 0.279 1.0 0.0
  # Siesta Calculations from Ben's Dissertation
  - type: lattice_constants
    data: [[5.11, 5.11, 13.58], [90, 90, 120]]
  - type: elastic_constants
    data: [[241,  92,  78,   9,   0,   0],
           [ 92, 241,  78,  -9,   0,   0],
           [ 78,  78, 232,   0,   0,   0],
           [  9,  -9,   0,  76,   0,   0],
           [  0,   0,   0,   0,  76,   9],
           [  0,   0,   0,   0,   9,  76]]
  - type: bulk_modulus
    data: 134.32
  - type: shear_modulus
    data:  76.18
  - type: point_defects
    data:
      # units are eV
      # taken from Ben's Dissertation (Fig. 4.11)
      # along the c axis whereas the Nb and Ta interstitials reside
      # slightly lower at 2.03Å.
      # split-interstial within the location for oxygen
      li_interstial:
        - {"opp": "+", "element": "Li", "position": [0.0, 0.0, 0.15], "energy": -2.5}
      ta_interstial:
        - {"opp": "+", "element": "Ta", "position": [0.0, 0.0, 0.15], "energy": -20.0}
      o_interstial:
        - {"opp": "+", "element": "O", "position": [0.0, 0.0, 0.15], "energy": -9.0}
      li_vacancy:
        - {"opp": "-", "element": "Li", "position": [0, 0, 0.279], "energy": -5.0}
      ta_vacancy:
        - {"opp": "-", "element": "Ta", "position": [0.0, 0.0, 0.0], "energy": -21.0}
      o_vacancy:
        - {"opp": "-", "element": "O", "position": [0.0501, 0.3436, 0.0687], "energy": -6.0}
  - type: displacement_energies
    data:
      # units are eV
      li_1: { "element": "Li", "position": [0, 0, 0.279], "direction": [1   , 0  ,  0   ], "energy":  5 }
      li_2: { "element": "Li", "position": [0, 0, 0.279], "direction": [0   , 1  ,  0   ], "energy": 18 }
      li_3: { "element": "Li", "position": [0, 0, 0.279], "direction": [0   , 0  ,  1   ], "energy": 30 }
      li_4: { "element": "Li", "position": [0, 0, 0.279], "direction": [0.43, 0.21, 0.88], "energy": 13 }
      li_5: { "element": "Li", "position": [0, 0, 0.279], "direction": [0.76, 0.36, 0.54], "energy": 15 }
      li_6: { "element": "Li", "position": [0, 0, 0.279], "direction": [0.75, 0   , 0.65], "energy": 30 }
      ta_1: { "element": "Ta", "position": [0.0, 0.0, 0.0], "direction": [1   , 0  ,  0   ], "energy": 17 }
      ta_2: { "element": "Ta", "position": [0.0, 0.0, 0.0], "direction": [0   , 1  ,  0   ], "energy": 21 }
      ta_3: { "element": "Ta", "position": [0.0, 0.0, 0.0], "direction": [0   , 0  ,  1   ], "energy": 29 }
      ta_4: { "element": "Ta", "position": [0.0, 0.0, 0.0], "direction": [0.43, 0.21, 0.88], "energy": 28 }
      ta_5: { "element": "Ta", "position": [0.0, 0.0, 0.0], "direction": [0.76, 0.36, 0.54], "energy": 23 }
      ta_6: { "element": "Ta", "position": [0.0, 0.0, 0.0], "direction": [0.75, 0   , 0.65], "energy": 28 }
      o_1:  { "element": "O",  "position": [0.0501, 0.3436, 0.0687], "direction": [1   , 0  ,  0   ], "energy": 29 }
      o_2:  { "element": "O",  "position": [0.0501, 0.3436, 0.0687], "direction": [0   , 1  ,  0   ], "energy": 22 }
      o_3:  { "element": "O",  "position": [0.0501, 0.3436, 0.0687], "direction": [0   , 0  ,  1   ], "energy": 18 }
      o_4:  { "element": "O",  "position": [0.0501, 0.3436, 0.0687], "direction": [0.43, 0.21, 0.88], "energy": 60 }
      o_5:  { "element": "O",  "position": [0.0501, 0.3436, 0.0687], "direction": [0.76, 0.36, 0.54], "energy": 16 }
      o_6:  { "element": "O",  "position": [0.0501, 0.3436, 0.0687], "direction": [0.75, 0   , 0.65], "energy": 50 }
  - type: melting_point
    data: 1923 # Kelvin
